### PR TITLE
Account optional deps

### PR DESCRIPTION
**Pull request by rvem**
Problem: Opam files have field for optional dependencies, which aren't
accounted currently. This may lead to an unexpected resulting binaries
and libraries behaviour.

Solution: Check opam file for `depopts` and uncoditionally (for now) add
all packages to the build dependencies.

### CODE REVIEW

**Comment by rvem** [comment]
However, the suggested approach has some drawbacks, sometimes unwanted dependencies are unconditionally added:(

**Comment by balsoft** [comment]
1. Does tezos-packaging build with this patch?
2. Does LIGO build with this patch (make sure that tezos-packaging has this patch applied too)?

If so, I deem this to be good enough, perhaps we can rewrite it later to allow to remove some optional depdencies.

**Comment by rvem** [comment]
1) No, I'm currently trying to apply some hacks to make it buildable

**Comment by rvem** [comment]
Apparently, it's quite obsolete now

**Pull request closed without merging**
